
# Setup
title:               anteater
email:               lhinds@protonmail.com
tagline:             DevOps Security Framework
url:                 "" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              Luke Hinds
  url:               https://twitter.com/lukeahinds
  email:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: anteater
twitter_username: lukeahinds
instagram_username: kevin/
facebook:
linkedin_username:
dribbble_username:

# Custom vars
version:             1.0
github:
  repo:              https://github.com/anteater/anteater.io

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty

widgets:
  - title: About
    url: about
    archor: true
  - title: Docs
    url: docs
    archor: true
  - title: Blog
    url: blog
  - title: Page
    url: page
